#!/bin/sh
# Maven Wrapper script for bumping version up
# ----------------------------------------------------------------------------

echo "Bumping version to $1"

./mvnw versions:set -DnewVersion="$1"
./mvnw -f msbotframework4j-parent/pom.xml versions:set -DnewVersion="$1"

echo "Finished"
